apiVersion: v2
name: auth-service
description: Helm chart for Mintify auth-service
type: application
version: 0.1.0         # chart version
appVersion: "0.2.0"    # app version (can be anything, keep in sync with your image tags if you want)
