app:
  name: auth-service

image:
  repository: junteak/mintify-auth-service
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4001

ingress:
  enabled: true
  className: traefik
  host: auth.ltu-m7011e-9.se
  path: /

env:
  KEYCLOAK_REALM: "mintify"
  KEYCLOAK_CLIENT_ID: "frontend"
  KEYCLOAK_ISSUER_URL: "https://example.com/realms/mintify"
