app:
  name: gateway-service
image:
  repository: junteak/mintify-gateway-service # <-- change if needed
  tag: "amd64-34b5bae" # <-- match your built tag
  pullPolicy: Always
service:
  type: ClusterIP
  port: 4000
ingress:
  enabled: true
  className: traefik
  host: gateway.ltu-m7011e-9.se # you can change this if you want
  path: /
