apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notif-service.fullname" . }}
  labels:
    {{- include "notif-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notif-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notif-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: notif-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            - name: PORT
              value: "{{ .Values.service.port }}"

            # ---- MongoDB ----
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mintify-shared-secret
                  key: MONGODB_URI

            - name: MONGODB_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mintify-shared-secret
                  key: MONGODB_DB_NAME

            # ---- RabbitMQ ----
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: mintify-shared-secret
                  key: RABBITMQ_URL

            - name: RABBITMQ_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: mintify-shared-secret
                  key: RABBITMQ_EXCHANGE

            - name: RABBITMQ_QUEUE
              value: "{{ .Values.env.rabbitmqQueue }}"
