apiVersion: v1
kind: Service
metadata:
  name: transact-service
  labels:
    app: transact-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: transact-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
