app:
  name: budget-service
image:
  repository: junteak/mintify-budget-service
  tag: "amd64-4637382"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 4002
ingress:
  enabled: true
  className: traefik
  host: budget.ltu-m7011e-9.se
  path: /
