app:
  name: frontend
image:
  repository: junteak/mintify-frontend
  tag: "amd64-f5d9b57" # <-- change to the new tag
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: traefik
  host: mintify.ltu-m7011e-9.se
  path: /
